#!/bin/bash

################################################################################
# This file is part of debian-zfs-root-script.
#
# debian-zfs-root-script is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 
# of the License, or (at your option) any later version.
#
# debian-zfs-root-script is distributed in the hope that it will 
# be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
################################################################################

mkdir -p /tmp/target

zpool import -f -R /tmp/target -N rpool
zpool import -f -R /tmp/target -N bpool

zfs mount rpool/ROOT/debian
mkdir -p /tmp/target/dev
mkdir -p /tmp/target/proc
mkdir -p /tmp/target/sys
mount --rbind /dev  /tmp/target/dev
mount --rbind /proc /tmp/target/proc
mount --rbind /sys  /tmp/target/sys
zfs mount bpool/BOOT/debian
zfs mount rpool/home
zfs mount rpool/home/root
zfs mount rpool/tmp
zfs mount rpool/var
zfs mount rpool/var/cache
zfs mount rpool/var/lib
zfs mount rpool/var/log
zfs mount rpool/var/spool
zfs mount rpool/var/tmp
if [ -d /sys/firmware/efi ]; then
  chroot /tmp/target mount /boot/efi
fi
