#!/bin/bash

################################################################################
# This file is part of debian-zfs-root-script.
#
# debian-zfs-root-script is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 
# of the License, or (at your option) any later version.
#
# debian-zfs-root-script is distributed in the hope that it will 
# be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
################################################################################

if [ -d /sys/firmware/efi ]; then
  chroot /tmp/target umount /boot/efi
fi
for mnt in dev sys proc; do
  umount --recursive --force --lazy /tmp/target/$mnt
done
mount | grep zfs | tac | awk '/\/tmp\/target/ {print $3}' | xargs -i{} umount -lf {}
zpool export -a
rmdir /tmp/target
